# Generated by Django 4.1.4 on 2022-12-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_quesito_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Risposte",
            new_name="Risposta",
        ),
        migrations.AlterModelOptions(
            name="risposta",
            options={"verbose_name_plural": "risposte"},
        ),
        migrations.RenameField(
            model_name="questionario",
            old_name="url",
            new_name="slug",
        ),
    ]
