# Generated by Django 4.1.4 on 2022-12-11 15:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_rename_risposte_risposta_alter_risposta_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quesito",
            name="conclusione",
            field=ckeditor.fields.RichTextField(default=""),
        ),
        migrations.AddField(
            model_name="quesito",
            name="introduzione",
            field=ckeditor.fields.RichTextField(default=""),
        ),
        migrations.AddField(
            model_name="questionario",
            name="conclusione",
            field=ckeditor.fields.RichTextField(default=""),
        ),
        migrations.AddField(
            model_name="questionario",
            name="introduzione",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
