# Generated by Django 4.1.4 on 2022-12-11 15:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_quesito_conclusione_quesito_introduzione_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quesito",
            name="conclusione",
            field=ckeditor.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="quesito",
            name="introduzione",
            field=ckeditor.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="quesito",
            name="opzioni",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="questionario",
            name="conclusione",
            field=ckeditor.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="questionario",
            name="introduzione",
            field=ckeditor.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="risposta",
            name="risposta",
            field=models.JSONField(null=True),
        ),
    ]
