# Generated by Django 4.1.4 on 2023-03-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_alter_quesito_opzioni_alter_risposta_risposta"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quesito",
            options={"ordering": ("order",), "verbose_name_plural": "quesiti"},
        ),
    ]
