# Generated by Django 4.1.4 on 2023-09-02 17:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_quesito_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesito',
            name='conclusione_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quesito',
            name='conclusione_it',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quesito',
            name='introduzione_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quesito',
            name='introduzione_it',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='quesito',
            name='titolo_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='quesito',
            name='titolo_it',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='conclusione_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='conclusione_it',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='introduzione_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='introduzione_it',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='titolo_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='titolo_it',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
